# This file was generated by GoReleaser. DO NOT EDIT.
cask "ocli" do
  version "1.1.3"

  on_macos do
    on_intel do
      sha256 "f2e9efa18dfbacf6bb22deae20da4df9ade71f30cf5cf6c24fa27387c8e5dcb7"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/opencli_Darwin_x86_64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
    on_arm do
      sha256 "168f0778ec976941508782796644cb57a9957e638cdbf01834ca8871be48dd15"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/opencli_Darwin_arm64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "80f2e5af4c5c83be35ccdd2e8983d8c3adbb5a59b718c7dafe5962e517e615e8"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/opencli_Linux_x86_64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
    on_arm do
      sha256 "fdd6b3007640f59ca85df1ad64a4ce2270913d176b21d01a9c4148fe662de916"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/opencli_Linux_arm64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
  end

  name "ocli"
  desc "CLI to manage OpenCLI Specification documents"
  homepage "https://opencli.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ocli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ocli"]
    end
  end

  # No zap stanza required

end
