# This file was generated by GoReleaser. DO NOT EDIT.
cask "ocli" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "498cd7c7d90b88d03c9f4bed2df6aa0302f809d9d588a987993310924cf9df2d"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/ocli_Darwin_x86_64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
    on_arm do
      sha256 "553c29a8efa4465f932e89a1cd04638d67d126c5507aa70ae656a1eadb451564"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/ocli_Darwin_arm64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "df0e66fcda17189aed6f26a466ac3afe42e5deedd32f2733d0654ae777f62f35"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/ocli_Linux_x86_64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
    on_arm do
      sha256 "8a19fb26cd0d86bbd50a90c912b8e6f973446649ce9a605fd1042fb0be9ed820"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/ocli_Linux_arm64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
  end

  name "ocli"
  desc "CLI to manage OpenCLI Specification documents"
  homepage "https://opencli.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ocli"
  manpage "ocli.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ocli"]
    end
  end

  # No zap stanza required

end
