# This file was generated by GoReleaser. DO NOT EDIT.
cask "ocli" do
  version "1.1.4"

  on_macos do
    on_intel do
      sha256 "e38844dd2910b92ea4aa356112cd044e1e831af6f68b0d8b1cbb027097dd4c8a"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/ocli_Darwin_x86_64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
    on_arm do
      sha256 "d1b1d891a877cc47e6f37360a7d873f9df118a369b4eae536338c33d9f250039"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/ocli_Darwin_arm64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
  end

  on_linux do
    on_intel do
      sha256 "08e2f50d2e5dfdaad0fbd7a51cfb45ec8dbd3a0f7113c2751ae7df59f95926a5"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/ocli_Linux_x86_64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
    on_arm do
      sha256 "a36146487bf68c60a714ec8a9f85a2fd5693f5a7ca637f88fa21a9857b80c43e"
      url "https://github.com/bcdxn/opencli/releases/download/v#{version}/ocli_Linux_arm64.tar.gz",
        verified: "github.com/opencli/opencli/"
    end
  end

  name "ocli"
  desc "CLI to manage OpenCLI Specification documents"
  homepage "https://opencli.dev"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ocli"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ocli"]
    end
  end

  # No zap stanza required

end
